[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.13",
    "pydantic>=2.11.7",
    "uvicorn[standard]>=0.30.1",
]

[project.scripts]
dev = "uvicorn main:app --reload --port 8000"
